### ISSUE TITLE
It works with old articles?

### ISSUE THREAD

**Issue by Mte90** [fourtonfish/alt-embed-tweet#1]
I enabled the plugin with the various keys but I see that in some articles there is no oembed detection.

* https://daniele.tech/2019/06/little-recap-from-wordcamp-europe-berlin-2019/

Let me know if I can do something to help debug it

**Comment by stefanbohacek** [comment]
Hi, thank you for trying out the plugin!

Is this article using a classic editor perhaps? Would you be able to export it using something like [wp cli](https://wp-cli.org/)?

```
wp export --post__in=POST_ID
```

**Comment by Mte90** [comment]
yes I am using the classic editor in the whole website, I can share to you the content in case.
Anyway I am not sure if the plugin works also in the few tweets as example.
As I can remember the oembed is generated on saving the article so maybe there aren't in the page?

**Comment by stefanbohacek** [comment]
I do see the plugin making a call to the `ftf_embed_tweet` action, but the response is blank for some reason.

![image](https://user-images.githubusercontent.com/3909390/107241997-84293b80-69f9-11eb-86f7-5245f058110d.png)


And the default Twitter script is not being removed, so there's a few things going wrong here. Could you please send the exported XML to stefan@fourtonfish.com so that I can have a better look?

Thank you, I really appreciate your help!

**Comment by Mte90** [comment]
email sent

**Comment by stefanbohacek** [comment]
Yep, got it, thank you! I'll follow up as soon as I can.

**Comment by stefanbohacek** [comment]
The issue was resolved, the plugin settings page will clarify that v2 of the Twitter API is needed and that user should include plugin's Bootstrap styles if they're using a customized version of Bootstrap.

I opened a [separate ticket for parsing tweets](https://github.com/fourtonfish/tweet-embeds-wordpress-plugin/issues/2) that were added as a URL.

@Mte90 Thank you for all your help.
